export default {
    name: 'b-icon',
    basic: ['increase', 'cross', 'arrow-left', 'passed', 'arrow'],
    outline: [
        'message-ban-o',
        'rate-o',
        'explain-o',
        'report-o',
        'scan-o',
        'collect-o',
        'message-o',
        'setting-o',
        'info-o',
        'user-o',
        'split-picture-o',
        'copy-o',
        'close-o',
        'add-o',
        'success-o',
        'round',
        'position',
        'more',
        'share',
        'collection',
        'search',
        'modify',
        'refresh',
    ],
    filled: [
        'ing',
        'tip',
        'show',
        'hide',
        'location',
        'success',
        'close',
        'moments',
        'email',
        'copy',
        'ding-talk',
        'download',
        'photo',
        'photograph',
        'wechat',
        'qq',
    ],
}
